const contractModel = {
  id: 'id',
  contractNum: 'contractNum',
  contractName: 'contractName',
  capitalSource: 'captitalSource',
  package: 'package',
  category: 'category',
  partner: 'partner',
  contractType: 'contractType',
  contractState: 'contractState',
  addendum: 'addendum',
  liquidateDate: 'liquidateDate',
  signingDate: 'signingDate',
  expectStartDate: 'expectStartDate',
  realStartDate: 'realStartDate',
  realFinishDate: 'realFinishDate',
  expectFinishDate: 'expectFinishDate',
  takeOverDate: 'takeOverDate',
  contractValue: 'contractValue',
  adjustContractValue: 'adjustContractValue',
  implementDate: 'implementDate',
  appendix: 'appendix',
  code: 'code',
  activity: 'activity',
  accountNumber: 'accountNumber',
  bank: 'bank',
  address: 'address',
};

export default contractModel;
